{{- if and .Values.admin.enabled (not .Values.admin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uptime-kuma.adminSecretName" . }}
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "uptime-kuma.adminSecretName" .)) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{ .Values.admin.existingSecretUsernameKey }}: {{ .Values.admin.username | default (get $secretData .Values.admin.existingSecretUsernameKey | b64dec) | default "admin" | quote }}
  {{ .Values.admin.existingSecretPasswordKey }}: {{ .Values.admin.password | default (get $secretData .Values.admin.existingSecretPasswordKey | b64dec) | default (randAlphaNum 32) | quote }}
{{- end }}
